# Generated by Django 5.2.8 on 2025-11-16 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('eliminationSystem', models.CharField(choices=[('group', 'Csoportkör'), ('elimination', 'Egyenes kieséses')], default='elimination', max_length=50)),
            ],
            options={
                'verbose_name': 'Szakasz',
                'verbose_name_plural': 'Szakaszok',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('gameMode', models.CharField(choices=[('8ball', '8 Ball'), ('snooker', 'Snooker')], default='8ball', max_length=50)),
            ],
            options={
                'verbose_name': 'Bajnokság',
                'verbose_name_plural': 'Bajnokságok',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.phase')),
            ],
            options={
                'verbose_name': 'Csoport',
                'verbose_name_plural': 'Csoportok',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfpURL', models.CharField(blank=True, max_length=255, null=True)),
                ('is_biro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profilok',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('start', 'Frame kezdete'), ('end', 'Frame vége'), ('next_player', 'Következő játékos'), ('score_update', 'Pontszám frissítés'), ('balls_potted', 'Golyók belövése'), ('faul', 'Hiba'), ('faul_and_next_player', 'Hiba és következő játékos'), ('cue_ball_left_table', 'Kijátszó golyó elhagyta az asztalt'), ('cue_ball_gets_positioned', 'Kijátszó golyó pozícionálása')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('turn_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ball_ids', models.JSONField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='api.profile')),
            ],
            options={
                'verbose_name': 'Mérkőzés esemény',
                'verbose_name_plural': 'Mérkőzés események',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('frames_to_win', models.PositiveIntegerField(default=5)),
                ('broadcastURL', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.group')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.phase')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='api.profile')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='api.profile')),
            ],
            options={
                'verbose_name': 'Mérkőzés',
                'verbose_name_plural': 'Mérkőzések',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_frames', to='api.match')),
                ('events', models.ManyToManyField(blank=True, to='api.matchevent')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames_won', to='api.profile')),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frame-ek',
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.tournament'),
        ),
    ]
