# Generated by Django 5.2.7 on 2025-11-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='player1_ball_group',
            field=models.CharField(blank=True, choices=[('full', 'Full (Solid)'), ('striped', 'Striped')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='player2_ball_group',
            field=models.CharField(blank=True, choices=[('full', 'Full (Solid)'), ('striped', 'Striped')], max_length=10, null=True),
        ),
    ]
